name: Update icon Version
on:
  schedule:
    - cron: '0 */2 * * *'
jobs:
  update-icon-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run Python Script
        run: |
          curl -sSL https://raw.githubusercontent.com/legendu-net/github_actions_scripts/main/update_version_dockerfile.py \
            | uv run --script - \
            --repo legendu-net/icon \
            --token ${{ secrets.GITHUBACTIONS }}

