name: Update icon Version
on:
  schedule:
    - cron: '0 */4 * * *'
jobs:
  update-icon-version:
    runs-on: self-hosted
    steps:
      - name: Clone Repository
        run: |
          curl -sSL https://raw.githubusercontent.com/legendu-net/github_actions_scripts/main/git_clone_repo.fish | fish
      - name: Run Python Script
        run: |
          ls -lha
          .github/update_icon_version.py
          ls -lha

