name: Update icon Version
on:
  schedule:
    - cron: '0 */4 * * *'
jobs:
  update-code-server-version:
    runs-on: self-hosted
    steps:
      - name: Clone Repository
        run: |
          pwd
          mkdir -p $(dirname $GITHUB_WORKSPACE)
          cd $(dirname $GITHUB_WORKSPACE)
          rm -rf docker-base
          git clone git@github.com:legendu-net/docker-base.git
          cd docker-base
          pwd
          ls -lha
      - name: Run Python Script
        run: |
          ls -lha
          .github/update_icon_version.py
          ls -lha

