name: Update icon Version
on:
  schedule:
    - cron: '0 */4 * * *'
jobs:
  update-code-server-version:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - name: Run Python Script
        run: .github/update_icon_version.py

